spring:
    application:
        name: micro-adversarial-search
    datasource:
        url: jdbc:h2:mem:ratelimitdb
        driverClassName: org.h2.Driver
        username: sa
        password: ""
    jpa:
        database-platform: org.hibernate.dialect.H2Dialect
        hibernate:
            ddl-auto: update
    h2:
        console:
            enabled: true # Habilita la consola web de H2 (opcional, para inspeccionar datos)
# Configuraci√≥n de logging
logging:
  level:
    root: WARN
    org.javig.micro_adversarial_search: DEBUG
    org.springframework: WARN
    org.hibernate: WARN
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
  file:
    name: logs/microprimes.log
    max-size: 100MB
    max-history: 30