spring:
  application:
    name: micro-adversarial-search
  datasource:
    url: jdbc:h2:mem:ratelimitdb
    driverClassName: org.h2.Driver
    username: sa
    password: ""
  jpa:
    hibernate:
      ddl-auto: update
  h2:
    console:
      enabled: true # Habilita la consola web de H2 (opcional, para inspeccionar datos)

  web:
    cors:
      enabled: false

# Configuraci√≥n de logging
logging:
  level:
    root: INFO
    es.jastxz.micro_adversarial_search: INFO
    org.springframework: INFO
    org.hibernate: INFO
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
  file:
    name: logs/microprimes.log
    max-size: 10MB
    max-history: 30

server:
  port: 0
  compression:
    enabled: true
  http2:
    enabled: true
  servlet:
    context-path: /
  tomcat:
    max-threads: 10
    min-spare-threads: 1
    connection-timeout: 20000

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    instance-id: ${spring.application.name}:${server.port}
    prefer-ip-address: true

management:
  endpoints:
    web:
      exposure:
        include: health,info,mappings
